name: magi
channels:
  - conda-forge
  - defaults
dependencies:
  - bjoern=3.0.1
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - falcon=2.0.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libev=4.25
  - libffi=3.2.1
  - ncurses=6.2
  - openssl=1.1.1d
  - pip=20.0.2
  - python=3.7.6
  - python_abi=3.7
  - readline=7.0
  - setuptools=46.0.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

